$SEC Header
$REM $DEFL STITLE SIDENT STYPE SGEOMTRY SQUANT SUNITS STIME SDESC1 SDESC4
$REM $DEFL SSPRSTR1 SCOLLNAME STITLE SUCSTRING1 SUCSTRING2 SIDENT SUCSTRING3 SGPSLATITUDE SGPSLONGITUD SGPSALTITUDE SUCSTRING10 SUCSTRING9 SQUANT SQUANTERR SUNITS SGEOMTRY STIME SSYSERR SSYSTERR SUCSTRING4
$GETL 1 1 0
"Filename:::|AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" #filename
"Report Generated On:::|DDDDDDDDD |TTTTTTTTTT" #datetime #datetime
"Laboratory:::|AAAAAAAAAAAAAAAA" SSPRSTR1
"Operator:::|AAAAAAAAAAAAAAAAAAAAAAAA" SCOLLNAME
"Sample Title:::|AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" STITLE
"Sample Identification:::|AAAAAAAAAAAAAAAA" SIDENT
"Sample Type:::|AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" SUCSTRING1
"Sample Component:::|AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" SUCSTRING2
"Sample Geometry:::|AAAAAAAAAAAAAAAA" SGEOMTRY
"Sample Location Type:::|AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" SUCSTRING10
"Sample Location:::|AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" SUCSTRING9
"Sample Community/County:::|AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" SUCSTRING3
"Sample Coordinates:::|FFFF.FFFFFF |FFFF.FFFFFF |FFFF.FFFFFF" SGPSLATITUDE SGPSLONGITUD SGPSALTITUDE
"Sample Comment:::|AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" SUCSTRING4
"Sample Size/Error:::|EEEEEEEEEE |EEEEEEEEEE |AAAAAAAAAAAAAAAA" SQUANT SQUANTERR SUNITS
"Sample Taken On:::|DDDDDDDDD |TTTTTTTTTT" STIME STIME
"Acquisition Started:::|DDDDDDDDD |TTTTTTTTTT" ASTIME ASTIME
"Live Time:::|FFFFFFF.F" ELIVE
"Real Time:::|FFFFFFF.F" EREAL
$SETE #FV1 ELIVE
$SETE #FV2 EREAL
$SETS #FV2 #FV1
$SETM #FV2 100
$SETD #FV2 EREAL
"Dead Time:::|FF.FF" #FV2
$SEC NID_Intf
$IF NIDFNID
$SETE #IV9 PRUSESTRLIB
$IFNOT #IV9
"Nuclide Library Used:::|AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" EXPLIB
$ENDIF
$IF #IV9
"Nuclide Library Used:::Internal Library"
$ENDIF
$SETE #IV11 NIDFCSCDONE

$SETE #SV3 ACTIVUNITS
$SETE #FV1 ACTIVMULT
$IFNOT #FV1
$SETE #FV1 1.0
$SETE #SV3 'uCi'
$ENDIF

$DEFL NLENERGY NLPEAK NLABUN NLACTVTY NLERR NLCOICF NLCOIAPP NLCOINOTI NIDCOIERR
$SETE #IV1 1
$SETE #IV5 14
$SETE #IV8 RECCNT(NCLNAME)
$SETE #FV2 #FV1
$SETM #FV2 1.0/EM
$REC 1 NCLNAME 1 0 #IV8
$REC 2 NCLCONFID 1 0 #IV8
$REC 3 NCLFIDENT 1 0 #IV8

$REC 7 NCLFPDCORRDN 1 0 #IV8
"+++INTR+++"
$BT #IV8 ! Begin nuclide loop
 $IF #REC3(#IV1) ! if nuclide identified A
  $SETE #IV2 0
  $SETE #IV4 1
  $SETE #IV9 ENTCNT(NCLLINE,#IV1)
  $TBL 1 NCLLINE #IV1 1 #IV9
  $SETE #IV3 #TBL1(1)

  $BT #IV9 ! Begin line loop
   $GETL 2 #IV3 0
   $SETE #IV7 NLFNOUSEWTM(#IV3,1)
   $SETE #IV12 #LIS2(2)
   $SETA #IV12 #REC7(#IV1)
   $REM --- #IV12 is now the OR of 'this line ID-ed' and 'this nuclide P/D corrected'
   $IFNOT #IV2 ! If this is the first line of the nuclide, print nuclide name and confid as well as line info B
    $IF #IV12 ! ID'd or P/D applied C
     $IFNOT #IV11 ! Coinc. Corr. not done D
      "|AAAAAAA |F.FFF  |FFFF.FF|FF.FF  |EEEEEEEEEEEE |EEEEEEEEEEEE" #REC1(#IV1)  #REC2(#IV1) #LIS2(1) #LIS2(3) #LIS2(4)/MU=#FV1 #LIS2(5)/MU=#FV2
     $ELSE ! Coinc corr done D
      $REM Check warning/error code
      $IFEQ #LIS2(9) 0  ! E
       $SETE #IV13 0 ! --- then there is no warning or error.
      $ELSE ! some problem; see how bad it is E
       $IFEQ #LIS2(9) 315 ! F
        $SETE #IV13 0 ! -- merely warning that det. characterization does not cover low energies
       $ELSE  ! F
	    $IFEQ #LIS2(9) 537199722 ! some lines did not match
		 $SETE #IV13 0
		$ELSE
         $SETE #IV13 1 ! -- a real problem
		$ENDIF
       $ENDIF ! F
      $ENDIF ! End of Check warning/error code E
      $REM Use results of evaluating code      
      $IFEQ #IV13 1 ! a real problem; print "err" G
        "|AAAAAAA |F.FFF  |FFFF.FF|FF.FF  |EEEEEEEEEEEE |EEEEEEEEEEEE err" #REC1(#IV1) #REC2(#IV1) #LIS2(1) #LIS2(3) #LIS2(4)/MU=#FV1 #LIS2(5)/MU=#FV2 
      $ELSE ! no warning or error, but see if missing or COI free G
       $IF #LIS2(7) ! CAM_L_NLCOIAPP = 1 -> COI applied (a valid number) H
        "|AAAAAAA |F.FFF  |FFFF.FF|FF.FF  |EEEEEEEEEEEE |EEEEEEEEEEEE|F.FFF" #REC1(#IV1) #REC2(#IV1) #LIS2(1) #LIS2(3) #LIS2(4)/MU=#FV1 #LIS2(5)/MU=#FV2 #LIS2(6)
       $ELSE ! COI not applied; print "miss" or "free" depending on CAM_L_NLCOINOTI H
        "|AAAAAAA |F.FFF  |FFFF.FF|FF.FF  |EEEEEEEEEEEE |EEEEEEEEEEEE |AAA" #REC1(#IV1) #REC2(#IV1) #LIS2(1) #LIS2(3) #LIS2(4)/MU=#FV1 #LIS2(5)/MU=#FV2 #LIS2(8)/TF=free:miss
       $ENDIF ! H
      $ENDIF ! G
     $ENDIF ! D
    $ELSE ! not IDd and no P/D; merely print line info C
     "|AAAAAAA |F.FFF  |FFFF.FF|FF.FF" #REC1(#IV1) #REC2(#IV1) #LIS2(1) #LIS2(3)
    $ENDIF ! C
   $ELSE ! not the first line of the nuclide; merely print line info B
    $IF #IV12 ! ID'd or P/D applied I
     $IFNOT #IV11 ! Coinc. Corr. not done J
      "                    |FFFF.FF|A|A|FF.FF  |EEEEEEEEEEEE |EEEEEEEEEEEE" #LIS2(1) #LIS2(2)/TF=*: #IV7/TF=@: #LIS2(3) #LIS2(4)/MU=#FV1 #LIS2(5)/MU=#FV2
     $ELSE ! Coinc corr done J
      $REM Check warning/error code
      $IFEQ #LIS2(9) 0 ! K
       $SETE #IV13 0 ! --- then there is no warning or error.
      $ELSE ! some problem; see how bad it is K *** 5/5/11 TLG Added test for 537199722 - some lines did not match ***
       $IFEQ #LIS2(9) 315 ! L
         $SETE #IV13 0 ! -- merely warning that det. characterization does not cover low energies
       $ELSE ! L
         $IFEQ #LIS2(9) 537199722 ! some lines did not match
             $SETE #IV13 0
         $ELSE
            $SETE #IV13 1 ! -- a real problem 
          $ENDIF
       $ENDIF ! L
      $ENDIF ! End of Check warning/error code K
      $REM Use results of evaluating code      
      $IFEQ #IV13 1 ! a real problem; print "err" M
       "                    |FFFF.FF|A|A|FF.FF  |EEEEEEEEEEEE |EEEEEEEEEEEE err" #LIS2(1) #LIS2(2)/TF=*: #IV7/TF=@: #LIS2(3) #LIS2(4)/MU=#FV1 #LIS2(5)/MU=#FV2
      $ELSE ! no warning or error, but see if missing or COI free M
       $IF #LIS2(7) ! CAM_L_NLCOIAPP = 1 -> COI applied (a valid number) N
        "                    |FFFF.FF|A|A|FF.FF  |EEEEEEEEEEEE |EEEEEEEEEEEE|F.FFF" #LIS2(1) #LIS2(2)/TF=*: #IV7/TF=@: #LIS2(3) #LIS2(4)/MU=#FV1 #LIS2(5)/MU=#FV2 #LIS2(6)
       $ELSE ! COI not applied; print "miss" or "free" depending on CAM_L_NLCOINOTI N
        "                    |FFFF.FF|A|A|FF.FF  |EEEEEEEEEEEE |EEEEEEEEEEEE |AAA" #LIS2(1) #LIS2(2)/TF=*: #IV7/TF=@: #LIS2(3) #LIS2(4)/MU=#FV1 #LIS2(5)/MU=#FV2 #LIS2(8)/TF=free:miss
       $ENDIF ! N
      $ENDIF ! M
     $ENDIF ! J
    $ELSE ! not IDd  and no P/D; merely print line info I
     "                    |FFFF.FF|A|A|FF.FF" #LIS2(1) #LIS2(2)/TF=*: #IV7/TF=@: #LIS2(3)
    $ENDIF ! I
   $ENDIF ! B
   $REM Finished printing line; increment counters
   $SETA #IV5 1
   $SETE #IV2 1
   $SETA #IV4 1
   $SETE #IV3 #TBL1(#IV4)   
  $ET ! End line loop
   
 $ENDIF ! End if nuclide identified; processing for 1 nuclide A
 $SETA #IV1 1 ! Increment nuclide counter 
$ET ! End nuclide loop
"---INTR---"

$DEFL TOLERANCE CONFID SIGMA PSDATE PEAKSTART PEAKEND
$GETL 1 1 0

$IF USEVARETOL
$SETE #FV3 VARTOLERANCE
"Energy Tolerance:::|FFF.FFF FWHM" #FV3
$ELSE
$SETE #FV3 TOLERANCE
$SETD #FV3 ECALCNV
"Energy Tolerance:::|FFF.FFF |AA" #FV3 ECALUNITS
$ENDIF
"Nuclide confidence index threshold:::|FF.FF" #LIS1(2)
"Errors quoted at:::|F.FFF" 1.0/EM
$ENDIF

$IF NIDFINTERF
	"+++INTF+++"
	$SETE #IV1 1
	$SETE #IV5 13
	$SETE #IV9 RECCNT(NCLNAME)
	$REC 1 NCLNAME 1 0 #IV9
	$REC 2 NCLCONFID 1 0 #IV9
	$REC 3 NCLWTMEAN 1 0 #IV9
	$REC 4 NCLWTMERR 1 0 #IV9
	$REC 5 NCLFINTFREJ 1 0 #IV9
	$REC 6 NCLFIDENT 1 0 #IV9
	$REC 7 NCLFPDCORRDN 1 0 #IV9
	$BT #IV9
	$SETE #IV7 0
	$SETE #IV4 ENTCNT(NCLLINE,#IV1)
	$TBL 1 NCLLINE #IV1 1 #IV4
	$SETE #IV10 #REC6(#IV1)
	$SETA #IV10 #REC5(#IV1)
	$SETE #IV2 1
	$BT #IV4
	$SETE #IV3 #TBL1(#IV2)
	$SETA #IV7 NLFNOUSEWTM(#IV3,1)
	$SETA #IV2 1
	$ET
	$IF #IV10
		$IFNOT #REC5(#IV1)
			$REM "Don't report zero activities"
			"|AAAAAAA|F.FFF     |EEEEEEEEEEEEE  |EEEEEEEEEEEEE" #REC1(#IV1) #REC2(#IV1) #REC3(#IV1)/MU=#FV1 #REC4(#IV1)/MU=#FV2
		$ELSE
			"  |AX  |AAAAAAA  |F.FFF" #REC7(#IV1)/TF=!: #REC1(#IV1) #REC2(#IV1)
		$ENDIF
	$SETA #IV5 1
	$ENDIF
	$SETA #IV1 1	
	$ET
	"---INTF---"
$ENDIF

$SEC MDADECLVL
$IF NIDFMDA
$DEFL DETNAME SGEOMTRY STITLE EXPLIB
$GETL 1 1 0
$SETE #IV9 PRUSESTRLIB
$SETE #SV3 ACTIVUNITS
$SETE #FV1 ACTIVMULT
$IFNOT #FV1
$SETE #FV1 1.0
$SETE #SV3 'uCi'
$ENDIF
"+++MDA+++"
$DEFL NLMDA NLENERGY NLPEAK NLABUN NLACTVTY NLDETLIMIT NLMDADECLVL
$SETE #IV1 1
$SETE #IV5 14
$SETE #IV9 RECCNT(NCLNAME)
$REC 1 NCLNAME 1 0 #IV9
$REC 2 NCLFIDENT 1 0 #IV9
$REC 3 NCLFSHORTHL 1 0 #IV9
$REC 4 NCLFNORPTMDA 1 0 #IV9
$REC 5 NCLMDA 1 0 #IV9
$REM Added this line for Parent daughter correction
$REC 7 NCLFPDCORRDN 1 0 #IV9

$BT #IV9
$IFNOT #REC4(#IV1)
$SETE #IV2 0
$SETE #IV4 1
$SETE #IV8 ENTCNT(NCLLINE,#IV1)
$TBL 1 NCLLINE #IV1 1 #IV8
$SETE #IV3 #TBL1(1)
$BT #IV8
$GETL 2 #IV3 0
$SETE #FV2 #LIS2(1)
$IFNOT #REC3(#IV1)
$SETD #FV2 #LIS2(6)
$SETM #FV2 #FV1
$SETM #FV2 #LIS2(7)
$ENDIF
$IFNOT #IV2
"|AAAAAAA |FFFF.FF |FF.FF |EEEEEEEEEE |EEEEEEEEE |EEEEEEEEEE |EEEEEEEEEE" #REC1(#IV1) #LIS2(2) #LIS2(4) #LIS2(1)/MU=#FV1 #REC5(#IV1)/MU=#FV1 #LIS2(5)/MU=#FV1 #FV2
$SETE #IV2 1
$ELSE
$REM Not first line.
"|FFFF.FF |FF.FF |EEEEEEEEEE            |EEEEEEEEEE |EEEEEEEEEE" #LIS2(2) #LIS2(4) #LIS2(1)/MU=#FV1 #LIS2(5)/MU=#FV1 #FV2
$ENDIF
$SETA #IV4 1
$SETE #IV3 #TBL1(#IV4)
$SETA #IV5 1
$ET
$ENDIF
$SETA #IV1 1
$ET
"---MDA---"
$ENDIF


